export const locations = [
  {
    id: 1,
    name: "Abidjan",
    city: "Abidjan",
    region: "Lagunes",
    country: "Côte d'Ivoire",
  },
  {
    id: 2,
    name: "Touajuile",
    city: "Touajuile",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 3,
    name: "Echram",
    city: "Echram",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 4,
    name: "Atar",
    city: "Atar",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 5,
    name: "Akawratt",
    city: "Akawratt",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 6,
    name: "Agjoujet",
    city: "Agjoujet",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 7,
    name: "Aleg",
    city: "Aleg",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 8,
    name: "Amourj",
    city: "Amourj",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 9,
    name: "Iguevane",
    city: "Iguevane",
    region: "Tiris Zemmour",
    country: "Mauritania",
  },
  {
    id: 10,
    name: "Tweijikit",
    city: "Tweijikit",
    region: "Inchiri",
    country: "Mauritania",
  },
  {
    id: 11,
    name: "Dweirara",
    city: "Dweirara",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 12,
    name: "Debelgui",
    city: "Debelgui",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 13,
    name: "Dwerara",
    city: "Dwerara",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 14,
    name: "Rkiz",
    city: "Rkiz",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 15,
    name: "Zweirat",
    city: "Zweirat",
    region: "Tiris Zemmour",
    country: "Mauritania",
  },
  {
    id: 16,
    name: "Fdeirck",
    city: "Fdeirck",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 17,
    name: "La frontières",
    city: "La frontières",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 18,
    name: "Dakhla",
    city: "Dakhla",
    region: "Western Sahara",
    country: "Disputed Territory",
  },
  {
    id: 19,
    name: "Rabouni",
    city: "Rabouni",
    region: "Tindouf",
    country: "Algeria",
  },
  {
    id: 20,
    name: "Souleimania",
    city: "Souleimania",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 21,
    name: "Sentour",
    city: "Sentour",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 22,
    name: "Essiyasse",
    city: "Essiyasse",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 23,
    name: "Chami",
    city: "Chami",
    region: "Dakhlet Nouadhibou",
    country: "Mauritania",
  },
  {
    id: 24,
    name: "Teintane",
    city: "Teintane",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 25,
    name: "Leweynatt",
    city: "Leweynatt",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 26,
    name: "Aioun",
    city: "Aioun",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 27,
    name: "El Ghayra",
    city: "El Ghayra",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 28,
    name: "El KERKARAT",
    city: "El KERKARAT",
    region: "Western Sahara",
    country: "Disputed Territory",
  },
  {
    id: 29,
    name: "Moudjéria",
    city: "Moudjéria",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 30,
    name: "Mederdra",
    city: "Mederdra",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 31,
    name: "Lmelzem",
    city: "Lmelzem",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 32,
    name: "Lmelgue",
    city: "Lmelgue",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 33,
    name: "Néma",
    city: "Néma",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 34,
    name: "Nimlane",
    city: "Nimlane",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 35,
    name: "Mbout",
    city: "Mbout",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 36,
    name: "Nbeika",
    city: "Nbeika",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 37,
    name: "Njajbenni",
    city: "Njajbenni",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 38,
    name: "Nouadhibou",
    city: "Nouadhibou",
    region: "Dakhlet Nouadhibou",
    country: "Mauritania",
  },
  {
    id: 39,
    name: "Nouakchott",
    city: "Nouakchott",
    region: "Nouakchott",
    country: "Mauritania",
  },
  {
    id: 40,
    name: "Newjenhe",
    city: "Newjenhe",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 41,
    name: "Niamey",
    city: "Niamey",
    region: "Niamey Capital District",
    country: "Niger",
  },
  {
    id: 42,
    name: "Bababé",
    city: "Bababé",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 43,
    name: "Barkeiwol",
    city: "Barkeiwol",
    region: "Assaba",
    country: "Mauritania",
  },
  {
    id: 44,
    name: "Bassikounou",
    city: "Bassikounou",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 45,
    name: "Bamako",
    city: "Bamako",
    region: "Bamako Capital District",
    country: "Mali",
  },
  {
    id: 46,
    name: "Bangou",
    city: "Bangou",
    region: "Assaba",
    country: "Mauritania",
  },
  {
    id: 47,
    name: "Boutilimite",
    city: "Boutilimite",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 48,
    name: "Bellewar",
    city: "Bellewar",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 49,
    name: "Bogué",
    city: "Bogué",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 50,
    name: "Bougadoum",
    city: "Bougadoum",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 51,
    name: "Boulenwar",
    city: "Boulenwar",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 52,
    name: "Bir oumgreine",
    city: "Bir oumgreine",
    region: "Tiris Zemmour",
    country: "Mauritania",
  },
  {
    id: 53,
    name: "Tamchekett",
    city: "Tamchekett",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 54,
    name: "Tidjikja",
    city: "Tidjikja",
    region: "Tagant",
    country: "Mauritania",
  },
  {
    id: 55,
    name: "Timbédra",
    city: "Timbédra",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 56,
    name: "Tiguent",
    city: "Tiguent",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 57,
    name: "Tindouve",
    city: "Tindouve",
    region: "Tindouf",
    country: "Algeria",
  },
  {
    id: 58,
    name: "Djigueni",
    city: "Djigueni",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 59,
    name: "Dakar",
    city: "Dakar",
    region: "Dakar",
    country: "Senegal",
  },
  {
    id: 60,
    name: "Rosso",
    city: "Rosso",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 61,
    name: "Sélibaby",
    city: "Sélibaby",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 62,
    name: "Cheguar",
    city: "Cheguar",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 63,
    name: "Chelket Demba",
    city: "Chelket Demba",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 64,
    name: "Choum",
    city: "Choum",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 65,
    name: "Sangrave",
    city: "Sangrave",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 66,
    name: "Adel begrou",
    city: "Adel begrou",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 67,
    name: "Elb elkheir",
    city: "Elb elkheir",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 68,
    name: "Fassala",
    city: "Fassala",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 69,
    name: "Virage",
    city: "Virage",
    region: "Nouakchott",
    country: "Mauritania",
  },
  {
    id: 70,
    name: "Virage Tamchekett",
    city: "Virage Tamchekett",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 71,
    name: "Kamour",
    city: "Kamour",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 72,
    name: "Guérou",
    city: "Guérou",
    region: "Assaba",
    country: "Mauritania",
  },
  {
    id: 73,
    name: "Kankoussa",
    city: "Kankoussa",
    region: "Assaba",
    country: "Mauritania",
  },
  {
    id: 74,
    name: "Koubenni",
    city: "Koubenni",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 75,
    name: "Cotonou",
    city: "Cotonou",
    region: "Littoral",
    country: "Benin",
  },
  {
    id: 76,
    name: "Gouraye",
    city: "Gouraye",
    region: "Guidimaka",
    country: "Mauritania",
  },
  {
    id: 77,
    name: "Gogui",
    city: "Gogui",
    region: "Hodh El Gharbi",
    country: "Mauritania",
  },
  {
    id: 78,
    name: "Gougui",
    city: "Gougui",
    region: "Hodh Ech Chargui",
    country: "Mauritania",
  },
  {
    id: 79,
    name: "Kolakh",
    city: "Kolakh",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 80,
    name: "Kiffa",
    city: "Kiffa",
    region: "Assaba",
    country: "Mauritania",
  },
  {
    id: 81,
    name: "Kaédi",
    city: "Kaédi",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 82,
    name: "Letfetal",
    city: "Letfetal",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 83,
    name: "Lekhdeirat",
    city: "Lekhdeirat",
    region: "Adrar",
    country: "Mauritania",
  },
  {
    id: 84,
    name: "Leweinat",
    city: "Leweinat",
    region: "Trarza",
    country: "Mauritania",
  },
  {
    id: 85,
    name: "Lexeiba",
    city: "Lexeiba",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 86,
    name: "Matam",
    city: "Matam",
    region: "Matam",
    country: "Senegal",
  },
  {
    id: 87,
    name: "Maghama",
    city: "Maghama",
    region: "Gorgol",
    country: "Mauritania",
  },
  {
    id: 88,
    name: "Magta Lahjar",
    city: "Magta Lahjar",
    region: "Brakna",
    country: "Mauritania",
  },
  {
    id: 89,
    name: "Ouagadougou",
    city: "Ouagadougou",
    region: "Centre",
    country: "Burkina Faso",
  },
];

export default locations;
